project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "Conformal Counterfactual Explanations"
  subtitle: "Online Companion"
  author: "Patrick Altmeyer"
  date: today
  chapters:
    - index.qmd
    # - notebooks/proposal.qmd
    - notebooks/intro.qmd
    - notebooks/references.qmd

bibliography: bib.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute: 
  echo: false
  eval: true
  output: false
  freeze: auto

jupyter: julia-1.8



