[artifacts-]
git-tree-sha1 = "c757fad1336914313574b87ee59db6b0d53ca176"
lazy = true

    [[artifacts-.download]]
    sha256 = "96a7550f4dabe3cd7eec5e21a0a56ec9b4283ab3f5f7f7da42716e2a12fa123d"
    url = "https://github.com/pat-alt/ECCCo.jl/releases/download/results-paper-submission-1.8.5/artifacts-.tar.gz"
