project:
  type: book
  output-dir: ../docs

book:
  title: "Conformal Counterfactual Explanations"
  subtitle: "Online Companion"
  author: "Patrick Altmeyer"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: ../bib.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute: 
  echo: false
  eval: true
  output: false
  freeze: auto

jupyter: julia-1.8



